!include ../Player.pu 

package PlayerStateControllerPackage
{
    interface IPlayerStateController
    {
        +StartState(Player player)
        +UpdateState()
    }
}

Player o-- IPlayerStateController
