!include ../Player.pu 

package PlayerStateControllerPackage
{
    interface IPlayerStateController
    {
        +StartState()
        +UpdateState(Player player)
    }
}

Player o-- IPlayerStateController
