!include PlayerStateController.pu 

package PlayerStatePackage 
{
    interface IPlayerState
    {
        + string StateName
        + Enter(Player owner, IPlayerState prevState)
        + Update(Player owner)
        + Exit(Player owner, IPlayerState nextState)
        + Setup(string stateName, Action<String> onChangeState)
    }
}

Player -- IPlayerState : "プレイヤーの状態を取得"
PlayerStateController "1" o-- "0..*" IPlayerState