!include IPlayerState.pu  

package PlayerStatePackage 
{
    abstract PlayerStateBase
    {
        - Action<string> onChangeState

        # ChangeState<T>() ここでクラスをstringに変換してコールバックを呼ぶ
    }
}

IPlayerState <|-- PlayerStateBase