!include IPlayerStateController.pu  

package PlayerStateControllerPackage
{
    abstract PlayerStateController
    {
        -IPlayerState currentState

        - IPlayerState idleState 
        - IPlayerState jumpState 
        - IPlayerState runState 
        - IPlayerState inSkyState 

        - ChangeState(string stateName)
    }
}

IPlayerStateController <|-- PlayerStateController 
