!include IPlayerColliderController.pu
!include PlayerColliderController.pu
!include PlayerCollider.pu
!include IColliderInfo.pu 

package PlayerColliderPackage
{
    PlayerColliderController o- PlayerShareCollider 
    note right : PlayerColliderを共有する
    PlayerColliderController o-- PlayerCollider
    PlayerShareCollider -- PlayerCollider : 共有する
    IPlayerCollider "1" o-- "1" IColliderInfo : "情報を持つ"
}