package PlayerPackage
{
    interface IPlayerTransform
    {
        + WrapVector2 velocity 
        + WrapVector2 position 
        + WrapVector2 direction
        + float speed
    }
}

WrapVector2 -- IPlayerTransform