!include IPlayerTransform.pu 
!include IPlayerInfo.pu 

package PlayerPackage
{
    abstract Player
    {
        /'変数'/
        - IPlayerStateController stateController
        
        + IPlayerColliderController colliderController
    }
}

IPlayerTransform <|-- Player
IPlayerInfo <|-- Player
IPlayerColliderController -- Player 