[*] -r-> 状態

state 状態{
    '何もしない ->
    何もしない --> 走る
    何もしない --> 攻撃
    何もしない --> ジャンプ
    何もしない --> 空中にいる : 落下

    '走る ->
    走る -> 何もしない

    '攻撃
    攻撃 -> 何もしない

    'ジャンプ
    ジャンプ --> 空中にいる

    '空中にいる
    空中にいる --> 何もしない : 地面判定
}

