!include ../PlayerStateBase.pu  

package PlayerStatePackage 
{
    class RunPlayerState
    {
        - Run(IPlayerTransform transform)
        - Flip(IPlayerTransform transform)
    }
}

PlayerStateBase <|-- RunPlayerState